# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Test pypi

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
          python-version: ["3.8", "3.9", "3.10", "3.11"]
          os: ["macos-11"]

    steps:
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install package
      run: |
        pip install --upgrade pip
        pip install --upgrade scipy statsmodels scikit-learn setuptools
        pip install --index-url https://test.pypi.org/simple/ libbiosmoother

    - name: Import package
      run: |
        python -c "import libbiosmoother; print(libbiosmoother.LIB_BIO_SMOOTHER_CPP_VERSION)"
        libbiosmoother -v