name: Test Install

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    needs: [publish-testpypi]
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
          python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
          os: ["ubuntu-latest", "windows-latest", "mac-latest"]

    steps:
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install package
      run: |
        pip install --upgrade pip
        pip install scipy statsmodels scikit-learn
        pip install --index-url https://test.pypi.org/simple/ libbiosmoother

    - name: Import package
      run: |
        python -c "import libbiosmoother; print(libbiosmoother.LIB_BIO_SMOOTHER_CPP_VERSION)"
        libbiosmoother -v